server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: message-service
      enable-auto-commit: false          # ðŸ”´ REQUIRED
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"

    listener:
      ack-mode: MANUAL                   # ðŸ”´ REQUIRED

  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: whatsapp
    local-datacenter: datacenter1
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
